### PR TITLE
changes to support start date when cron string has an interval in date

### PR DESCRIPTION
**Pull request by hjjo**
for example, 
'0 0 1/2 * *' should trigger on every two days starts from the first day of the month.

see here to refer the cron expressions
https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm
and here
https://www.baeldung.com/cron-expressions

### CODE REVIEW

**Comment by roccivic** [comment]
I don't see this syntax being supported anywhere. The docs you linked to don't show this either.

I tried to use the expression you provided in Jenkins and got a syntax error.

capture

**Comment by hjjo** [comment]
Could you please “0 0 0 1/2 * ?”
I tested it here.
https://www.freeformatter.com/cron-expression-generator-quartz.html

**Comment by roccivic** [comment]
Quartz syntax is not supported by this module. It is radically different by the POSIX/Jenkins syntax that this module was written for. The pull request you submitted does not implement the entire quartz syntax.

I recommend that you either create an entirely new module to support the quartz syntax.

**Comment by hjjo** [comment]
Thanks for your advice, I decided to change our cron strings to more general use cases like "0 0 */2 * *" and "0 0 2-31/2 * *" which were "0 0 1/2 * *" and "0 0 2/2 * *" before.

**Pull request closed without merging**
