### PR TITLE
Fix parsing and converting

### LINKED ISSUE #10: toString parsing error on day of week step
Error when parsing array specifically on day of week, step expression

Parse [1, 3, 5]
Result when toString() should be 1/2 or just plain 1,3,5

Instead, the result is */2, which is effectively [0, 2, 4, 6].
Not sure if problem with parsing or when displaying to string.

Might also be the same for hours and minutes

Edit: Looks like the problem lies when converting to string

### PR DESCRIPTION
**Pull request by Vija02**
Fix on isFullInterval returning true even when not full
Fix on applyInterval not parsing partial step (eg: 1-5/2) correctly
closes #10

### CODE REVIEW

**Comment by roccivic** [comment]
@Vija02 Some unit tests are failing on this PR. If you could fix that up and perhaps add some regression tests, that would be great. Thanks.

**Comment by Vija02** [comment]
@roccivic Should be ok now 😄. Your tests are enough to make sure it's working properly. I merely fixed some wrong behaviors on steps.

**Comment by Vija02** [comment]
There are some credential problem on zuul. I don't think i can do anything about that?

**Comment by roccivic** [comment]
@Vija02 Looks good, thanks for the PR.

Zuul builds always fail unless they are ran from my repo, so no problems there.

**Pull request merged**
